function createfigurePathological(X1, Y1, X2, Y2, X3, Y3, X4, Y4)
%CREATEFIGURE(X1,Y1,X2,Y2,X3,Y3,X4,Y4)
%  X1:  vector of x data
%  Y1:  vector of y data
%  X2:  vector of x data
%  Y2:  vector of y data
%  X3:  vector of x data
%  Y3:  vector of y data
%  X4:  vector of x data
%  Y4:  vector of y data

%  Auto-generated by MATLAB on 15-Apr-2011 22:14:19

% Create figure

figure1 = figure('Name','Pathological function');
scrsz = get(0,'ScreenSize')    %determines size of monitor=left,bottom,width,height
set(gcf,'OuterPosition',[1 100 scrsz(3)-200 scrsz(4)-200]) 

% Create axes
axes1 = axes('Parent',figure1,'YMinorTick','on','YGrid','on',...
    'XMinorTick','on',...
    'XGrid','on',...
    'Position',[0.162162162162162 0.133640552995392 0.742837837837838 0.791359447004608],...
    'FontSize',20);
% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[-2.10737928547011e-020 2.4451701422094e-020]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[29.3506063211491 29.6733017659014]);
box(axes1,'on');
hold(axes1,'all');

% Create plot
plot(X1,Y1,'Color',[0 0 1]);

% Create plot
plot(X2,Y2,'Color',[0 1 0]);

% Create plot
plot(X3,Y3,'Color',[1 0 0]);

% Create plot
plot(X4,Y4,'Color',[0 1 1]);

% Create xlabel
xlabel('x+pi','FontSize',24);

% Create ylabel
ylabel('value of pathological function','FontSize',30);

% Create title
title('Pathological function');

% Create arrow
annotation(figure1,'arrow',[0.359073359073359 0.461389961389962],...
    [0.52073732718894 0.200460829493088]);

% Create textbox
annotation(figure1,'textbox',...
    [0.312827956989247 0.517615176151762 0.279645161290323 0.0420054200542005],...
    'String',{'There is a zero hiding here!!!!'},...
    'FontSize',14,...
    'FontName','High Tower Text',...
    'FitBoxToText','off');

